[package]
name = "immersion_control_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.51.0"
vulkano = "0.33.0"
winit = "0.28.3"